(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



massCOM[boat_] := Module[{densityOfFoam,foamMass,foamPoint,newPoints,newMasses},
densityOfFoam = QuantityMagnitude[UnitConvert[Quantity[31.7,("Kilograms")/("Meters")^3], "Grams"/"Centimeters"^3]];
(*center1 = Total[Cross[points,masses]] / Total[masses]
center2 = RegionCentroid[region]*)
foamMass=Volume[region/.boat] * densityOfFoam;
foamPoint=RegionCentroid[region/.boat];
newPoints = Append[massPts/.boat,foamPoint];
newMasses = Append[masses/.boat,foamMass];
(*allPoints=Join[Table[points[[i]]*masses[[i]],{i,Length@points}]  ,Cross[RegionCentroid[region],densityOfFoam]];*)
Total[Table[newPoints[[i]]*newMasses[[i]],{i,Length@newPoints}]] / Total[newMasses]

];


totalMass[boat_]:=Module[{densityOfFoam,foamMass,newMasses},
densityOfFoam = QuantityMagnitude[UnitConvert[Quantity[31.7,("Kilograms")/("Meters")^3], "Grams"/"Centimeters"^3]];
(*center1 = Total[Cross[points,masses]] / Total[masses]
center2 = RegionCentroid[region]*)
foamMass=Volume[region/.boat] * densityOfFoam;
newMasses = Append[masses/.boat,foamMass];
(*allPoints=Join[Table[points[[i]]*masses[[i]],{i,Length@points}]  ,Cross[RegionCentroid[region],densityOfFoam]];*)
Total[newMasses]

];



