(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



ClearAll[cob];
cobinner[region_,angle_,waterHeight_]:=Module[{nangle,pts,centroid},
nangle=Normalize[angle];
pts=myRandomPoint[region,nPoints];
underwaterPts=Cases[pts,pt_/;nangle.pt<waterHeight];
centroid=Total[underwaterPts]/Length[underwaterPts]
]

cob[region_,angle_,desiredVolume_]:=Module[{waterHeight},
waterHeight=waterline[region,angle,desiredVolume];
cobinner[region,angle,waterHeight]
]

rightingMoment[cob_,com_,up_,front_]:=Module[{left,r},
left = Normalize[up\[Cross]front];
r=cob-com;
r.left
]

rightingArm[region_,com_,\[Theta]_,desiredVolume_,front_]:=Module[{up},
up=RotationMatrix[\[Theta],front].{0,0,1};
rightingMoment[cob[region,up,desiredVolume],com,up,front]
]


rightingArm[boat_,front_,\[Theta]_]:=Module[{up,desiredVolume},
up=RotationMatrix[\[Theta],front].{0,0,1};
desiredVolume=totalMass[boat];
rightingMoment[cob[region/.boat,up,desiredVolume],massCOM[boat],up,front]
]



